name: Hysia
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.1.0
  - absl-py=0.8.0
  - astor=0.8.0
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2019.8.28
  - cairo=1.14.12
  - certifi=2019.9.11
  - cffi=1.12.3
  - cloudpickle=1.2.2
  - cudatoolkit=9.0
  - cudnn=7.6.0
  - cupti=9.0.176
  - cycler=0.10.0
  - cython=0.29.13
  - cytoolz=0.10.0
  - dask-core=2.5.0
  - dbus=1.13.6
  - decorator=4.4.0
  - django=2.1.5
  - expat=2.2.6
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.9.1
  - gast=0.3.2
  - glib=2.56.2
  - graphite2=1.3.13
  - grpcio=1.16.1
  - grpcio-tools=1.16.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - imageio=2.5.0
  - intel-openmp=2019.4
  - jasper=2.0.14
  - jpeg=9b
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.37
  - libprotobuf=3.9.2
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
  - markdown=3.1.1
  - matplotlib=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - ncurses=6.1
  - networkx=2.3
  - ninja=1.9.0
  - numpy=1.17.2
  - numpy-base=1.17.2
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1d
  - pandas=0.25.1
  - patsy=0.5.1
  - pcre=8.43
  - pillow=6.1.0
  - pip=19.2.3
  - pixman=0.38.0
  - protobuf=3.9.2
  - psutil=5.6.3
  - py-cpuinfo=5.0.0
  - py-opencv=3.4.2
  - pybind11=2.4.2
  - pycparser=2.19
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - python=3.6.9
  - python-dateutil=2.8.0
  - pytorch=0.4.1
  - pytz=2019.2
  - pywavelets=1.0.3
  - pyyaml=3.13
  - qt=5.9.7
  - readline=7.0
  - scikit-image=0.15.0
  - seaborn=0.9.0
  - setuptools=41.2.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.29.0
  - statsmodels=0.10.1
  - tensorboard=1.9.0
  - tensorflow=1.9.0
  - tensorflow-base=1.9.0
  - tensorflow-gpu=1.9.0
  - termcolor=1.1.0
  - tk=8.6.8
  - toolz=0.10.0
  - torchvision=0.2.1
  - tornado=6.0.3
  - tqdm=4.36.1
  - werkzeug=0.16.0
  - wheel=0.33.6
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - asgiref==3.2.2
    - asn1crypto==1.0.0
    - attrs==19.2.0
    - audioread==2.1.8
    - autobahn==19.10.1
    - automat==0.7.0
    - channels==2.3.0
    - click==7.0
    - constantly==15.1.0
    - cryptography==2.7
    - daphne==2.3.0
    - django-cors-headers==3.1.1
    - django-crispy-forms==1.7.2
    - django-rest-framework==0.1.0
    - djangorestframework==3.10.3
    - easydict==1.8
    - faiss-gpu==1.6.0
    - gputil==1.4.0
    - hyperlink==19.0.0
    - idna==2.6
    - imageio-ffmpeg==0.3.0
    - incremental==17.5.0
    - joblib==0.14.0
    - librosa==0.6.2
    - llvmlite==0.29.0
    - numba==0.45.1
    - pyhamcrest==1.9.0
    - resampy==0.2.2
    - service-identity==18.1.0
    - scenedetect==0.5.1.1
    - scikit-learn==0.21.3
    - scipy==1.3.1
    - soundfile==0.10.2
    - tensorflow-hub==0.1.1
    - twisted==19.7.0
    - txaio==18.8.1
    - zope-interface==4.6.0
prefix: /home/lym/anaconda3/envs/Hysia

